CREATE TABLE `tradeWatchlist` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`optionType` enum('CE','PE') NOT NULL,
	`strikePrice` int NOT NULL,
	`expiryDate` varchar(20) NOT NULL,
	`entryPrice` varchar(20) NOT NULL,
	`entryDate` timestamp NOT NULL,
	`quantity` int NOT NULL,
	`stopLoss` varchar(20) NOT NULL,
	`target1` varchar(20) NOT NULL,
	`target2` varchar(20),
	`delta` varchar(20),
	`gamma` varchar(20),
	`theta` varchar(20),
	`vega` varchar(20),
	`iv` varchar(20),
	`status` enum('active','closed') NOT NULL DEFAULT 'active',
	`exitPrice` varchar(20),
	`exitDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tradeWatchlist_id` PRIMARY KEY(`id`)
);
